version: "3.9"

services:
  webapp:
    build: ./
    command: flask run --host=0.0.0.0
    environment:
      FLASK_APP: hello
      FLASK_ENV: development
    expose:
      - 5000
    ports:
      - 8080:5000
    volumes:
      - ./:/app
